-- -- Automatically generated packer.nvim plugin loader code

-- if vim.api.nvim_call_function('has', {'nvim-0.5'}) ~= 1 then
--   vim.api.nvim_command('echohl WarningMsg | echom "Invalid Neovim version for packer.nvim! | echohl None"')
--   return
-- end

-- vim.api.nvim_command('packadd packer.nvim')

-- local no_errors, error_msg = pcall(function()

-- _G._packer = _G._packer or {}
-- _G._packer.inside_compile = true

-- local time
-- local profile_info
-- local should_profile = false
-- if should_profile then
--   local hrtime = vim.loop.hrtime
--   profile_info = {}
--   time = function(chunk, start)
--     if start then
--       profile_info[chunk] = hrtime()
--     else
--       profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
--     end
--   end
-- else
--   time = function(chunk, start) end
-- end

-- local function save_profiles(threshold)
--   local sorted_times = {}
--   for chunk_name, time_taken in pairs(profile_info) do
--     sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
--   end
--   table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
--   local results = {}
--   for i, elem in ipairs(sorted_times) do
--     if not threshold or threshold and elem[2] > threshold then
--       results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
--     end
--   end
--   if threshold then
--     table.insert(results, '(Only showing plugins that took longer than ' .. threshold .. ' ms ' .. 'to load)')
--   end

--   _G._packer.profile_output = results
-- end

-- time([[Luarocks path setup]], true)
-- local package_path_str = "/home/elmm/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/elmm/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/elmm/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/elmm/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
-- local install_cpath_pattern = "/home/elmm/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
-- if not string.find(package.path, package_path_str, 1, true) then
--   package.path = package.path .. ';' .. package_path_str
-- end

-- if not string.find(package.cpath, install_cpath_pattern, 1, true) then
--   package.cpath = package.cpath .. ';' .. install_cpath_pattern
-- end

-- time([[Luarocks path setup]], false)
-- time([[try_loadstring definition]], true)
-- local function try_loadstring(s, component, name)
--   local success, result = pcall(loadstring(s), name, _G.packer_plugins[name])
--   if not success then
--     vim.schedule(function()
--       vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
--     end)
--   end
--   return result
-- end

-- time([[try_loadstring definition]], false)
-- time([[Defining packer_plugins]], true)
-- _G.packer_plugins = {
--   ["alpha-nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/alpha-nvim",
--     url = "https://github.com/goolord/alpha-nvim"
--   },
--   ["auto-pairs"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/auto-pairs",
--     url = "https://github.com/jiangmiao/auto-pairs"
--   },
--   ["awesome-vim-colorschemes"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/awesome-vim-colorschemes",
--     url = "https://github.com/rafi/awesome-vim-colorschemes"
--   },
--   ["bufferline.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/bufferline.nvim",
--     url = "https://github.com/akinsho/bufferline.nvim"
--   },
--   ["coc.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/coc.nvim",
--     url = "https://github.com/neoclide/coc.nvim"
--   },
--   ["friendly-snippets"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/friendly-snippets",
--     url = "https://github.com/rafamadriz/friendly-snippets"
--   },
--   fzf = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/fzf",
--     url = "https://github.com/junegunn/fzf"
--   },
--   ["fzf.vim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/fzf.vim",
--     url = "https://github.com/junegunn/fzf.vim"
--   },
--   ["gitsigns.nvim"] = {
--     config = { "\27LJ\2\n:\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\rgitsigns\frequire\0" },
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/gitsigns.nvim",
--     url = "https://github.com/lewis6991/gitsigns.nvim"
--   },
--   gruvbox = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/gruvbox",
--     url = "https://github.com/morhetz/gruvbox"
--   },
--   ["monokai.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/monokai.nvim",
--     url = "https://github.com/tanvirtin/monokai.nvim"
--   },
--   nerdtree = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/nerdtree",
--     url = "https://github.com/scrooloose/nerdtree"
--   },
--   ["nvim-autopairs"] = {
--     config = { "\27LJ\2\n@\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\19nvim-autopairs\frequire\0" },
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/nvim-autopairs",
--     url = "https://github.com/windwp/nvim-autopairs"
--   },
--   ["nvim-web-devicons"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/nvim-web-devicons",
--     url = "https://github.com/kyazdani42/nvim-web-devicons"
--   },
--   ["onedark.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/onedark.nvim",
--     url = "https://github.com/navarasu/onedark.nvim"
--   },
--   onehalf = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/onehalf/vim",
--     url = "https://github.com/sonph/onehalf"
--   },
--   ["packer.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/packer.nvim",
--     url = "https://github.com/wbthomason/packer.nvim"
--   },
--   ["plenary.nvim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/plenary.nvim",
--     url = "https://github.com/nvim-lua/plenary.nvim"
--   },
--   ["rose-pine"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/rose-pine",
--     url = "https://github.com/rose-pine/neovim"
--   },
--   ["vim-airline"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-airline",
--     url = "https://github.com/vim-airline/vim-airline"
--   },
--   ["vim-airline-themes"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-airline-themes",
--     url = "https://github.com/vim-airline/vim-airline-themes"
--   },
--   ["vim-commentary"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-commentary",
--     url = "https://github.com/tpope/vim-commentary"
--   },
--   ["vim-devicons"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-devicons",
--     url = "https://github.com/ryanoasis/vim-devicons"
--   },
--   ["vim-easymotion"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-easymotion",
--     url = "https://github.com/easymotion/vim-easymotion"
--   },
--   ["vim-go"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-go",
--     url = "https://github.com/fatih/vim-go"
--   },
--   ["vim-gradle"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-gradle",
--     url = "https://github.com/hdiniz/vim-gradle"
--   },
--   ["vim-maven-plugin"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-maven-plugin",
--     url = "https://github.com/mikelue/vim-maven-plugin"
--   },
--   ["vim-nerdtree-syntax-highlight"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-nerdtree-syntax-highlight",
--     url = "https://github.com/tiagofumo/vim-nerdtree-syntax-highlight"
--   },
--   ["vim-rainbow"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-rainbow",
--     url = "https://github.com/frazrepo/vim-rainbow"
--   },
--   ["vim-rooter"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-rooter",
--     url = "https://github.com/airblade/vim-rooter"
--   },
--   ["vim-snippets"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-snippets",
--     url = "https://github.com/honza/vim-snippets"
--   },
--   ["vim-styled-components"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-styled-components",
--     url = "https://github.com/styled-components/vim-styled-components"
--   },
--   ["vim-surround"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-surround",
--     url = "https://github.com/tpope/vim-surround"
--   },
--   ["vim-system-copy"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-system-copy",
--     url = "https://github.com/christoomey/vim-system-copy"
--   },
--   ["vim-test"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-test",
--     url = "https://github.com/vim-test/vim-test"
--   },
--   ["vim-tmux-navigator"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-tmux-navigator",
--     url = "https://github.com/christoomey/vim-tmux-navigator"
--   },
--   ["vim-visual-multi"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-visual-multi",
--     url = "https://github.com/mg979/vim-visual-multi"
--   },
--   ["vim-vsnip"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vim-vsnip",
--     url = "https://github.com/hrsh7th/vim-vsnip"
--   },
--   vimspector = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vimspector",
--     url = "https://github.com/puremourning/vimspector"
--   },
--   ["vista.vim"] = {
--     loaded = true,
--     path = "/home/elmm/.local/share/nvim/site/pack/packer/start/vista.vim",
--     url = "https://github.com/liuchengxu/vista.vim"
--   }
-- }

-- time([[Defining packer_plugins]], false)
-- -- Runtimepath customization
-- time([[Runtimepath customization]], true)
-- vim.o.runtimepath = vim.o.runtimepath .. ",/home/elmm/.local/share/nvim/site/pack/packer/start/onehalf/vim"
-- time([[Runtimepath customization]], false)
-- -- Config for: nvim-autopairs
-- time([[Config for nvim-autopairs]], true)
-- try_loadstring("\27LJ\2\n@\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\19nvim-autopairs\frequire\0", "config", "nvim-autopairs")
-- time([[Config for nvim-autopairs]], false)
-- -- Config for: gitsigns.nvim
-- time([[Config for gitsigns.nvim]], true)
-- try_loadstring("\27LJ\2\n:\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\rgitsigns\frequire\0", "config", "gitsigns.nvim")
-- time([[Config for gitsigns.nvim]], false)

-- _G._packer.inside_compile = false
-- if _G._packer.needs_bufread == true then
--   vim.cmd("doautocmd BufRead")
-- end
-- _G._packer.needs_bufread = false

-- if should_profile then save_profiles() end

-- end)

-- if not no_errors then
--   error_msg = error_msg:gsub('"', '\\"')
--   vim.api.nvim_command('echohl ErrorMsg | echom "Error in packer_compiled: '..error_msg..'" | echom "Please check your config for correctness" | echohl None')
-- end
